language: python

stages:
  - black
  - test

python:
  - "3.7"

jobs:
  include:
    - stage: black
      python: "3.7"
      script:
        - black --version
        - black .
  allow_failures:
    - python: "3.7"
  fast_finish: true

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python3 -m unittest discover -b
